/* This file was generated by lv6 version v6.110.2. */
/*  lv6 assert.lus -n assertExpr -2c */
/* on LAPTOP-B8CFCGII the 27/01/2025 at 21:09:46 */
#include "assert_assertExpr.h"
//// Defining step functions
// Step function(s) for assert_assertExpr_ctx
void assert_assertExpr_step(_integer i1,_integer i2,_integer *o){
   _boolean _X_1;

  _X_1 = i2 != 0;
  *o = i1 / i2;

#ifndef _DONT_CHECK_LUSTRE_ASSERTIONS
  if (!_X_1) printf("#Warning: a Lustre assertion has been violated in /home/fangda/proj/personal/Scade6Learning/lustre_core/eq_and_assert/assert.lus line:7, col:2 to 7\n");
#endif

} // End of assert_assertExpr_step

