/* This file was generated by lv6 version v6.110.2. */
/*  lv6 assert.lus -n assertExpr -2c */
/* on LAPTOP-B8CFCGII the 27/01/2025 at 21:09:46 */

#include "assert_assertExpr_loop_io.h"

/* Main procedure *************************/
int main(){
  int _s = 0;
  _integer i1;
  _integer i2;
  _integer o;
  

  print_rif_declaration();

  ISATTY = isatty(0);
  /* Main loop */
  while(1){
    if (ISATTY) printf("#step %d \n", _s+1);
    else if(_s) printf("\n");
    fflush(stdout);
    ++_s;

    get_inputs( &i1, &i2);
    assert_assertExpr_step(i1,i2,&o);
    print_outputs(o);
    // printf("%d %d #outs %d\n",i1,i2,o);
  }
  return 1;

}
