/* This file was generated by lv6 version v6.110.2. */
/*  lv6 assert.lus -n assertExpr -2c */
/* on LAPTOP-B8CFCGII the 27/01/2025 at 21:09:46 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lustre_consts.h"

// User typedef
#ifndef _assert_assertExpr_TYPES
#define _assert_assertExpr_TYPES
// Memoryfull soc ctx typedef 
void assert_assertExpr_step(_integer ,_integer ,_integer *);

/////////////////////////////////////////////////
#endif // end of  _assert_assertExpr_TYPES
