/* This file was generated by lv6 version v6.110.2. */
/*  lv6 assert.lus -n assertExpr -2c */
/* on LAPTOP-B8CFCGII the 27/01/2025 at 21:09:46 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES